### PR TITLE
Add PUT and DELETE to API CORS methods

### PR DESCRIPTION
**Pull request by lrasmus**
PUT and DELTE were not in the list of allowed CORS methods.  Although these are potentially modifying/destructive methods, because POST was already listed it seemed plausible that they could be too.

Are there security implications in the original design of Leaf why these were not include initially?

### CODE REVIEW

**Comment by ndobb** [comment]
@lrasmus I can't think of any particular security implications in a federate context. @cspital, can you think of any potential issues with adding PUT and DELETE? I don't recall exactly why we omitted them in this case.

**Comment by cspital** [comment]
I don't know if there was a reason for their omission. I THINK there are policies in place in the authorization setup that identify BOTH the role required to make change via the API and that they're institutional. Just need to make sure that API methods that modify data are constrained in that way.

**Comment by ndobb** [comment]
Got it. @lrasmus I'll review the API methods this week and merge if there are no problems (I suspect there are not)

**Comment by lrasmus** [comment]
Thanks! Apologies for the blind PR here as well - I typically would try to investigate this myself, but it seemed there would be historical knowledge that could be helpful in the review.

**Pull request merged**
